# exports/excel_export.py
import io
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils.dataframe import dataframe_to_rows

def df_to_formatted_xlsx_bytes(df, title="Atlas Export", subtitle=""):
    wb = Workbook()
    ws = wb.active
    ws.title = "Table"

    ws["A1"] = title
    ws["A2"] = subtitle
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"].font = Font(italic=True, size=10)

    start_row = 4
    for r_idx, row in enumerate(dataframe_to_rows(df, index=False, header=True), start=start_row):
        ws.append(row)
        if r_idx == start_row:
            for c in range(1, len(row) + 1):
                cell = ws.cell(row=r_idx, column=c)
                cell.font = Font(bold=True)
                cell.fill = PatternFill("solid", fgColor="DDDDDD")
                cell.alignment = Alignment(horizontal="center")

    ws.freeze_panes = f"A{start_row+1}"

    # Column widths
    for col in ws.columns:
        col_letter = col[0].column_letter
        max_len = 0
        for cell in col:
            if cell.value is not None:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 2, 40)

    meta = wb.create_sheet("Metadata")
    meta["A1"] = "Generated by Atlas"
    meta["A2"] = "Export type: Formatted table"

    bio = io.BytesIO()
    wb.save(bio)
    return bio.getvalue()
